files: \.(json)$
exclude: (package-lock\.json|\.vscode/.*\.json)$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-json
        name: Check JSON syntax
    -   id: pretty-format-json
        name: Format JSON files
        args: [--autofix, --indent=2, --no-sort-keys]